### PR TITLE
Basic Session support

### PR DESCRIPTION
**Pull request by jakob-ledermann**
I found some solutions to partially support sessions:
1. I managed to get to use a full duplex connection between client and server (OverlappedIO did enable the operations)
2. It is possible to call `list-sessions` and get a list of the running and past sessions
3. It is possible to attach to a running sessions

Not yet implemented or tested:

- [ ] resurrect a past session
- [ ] kill session
- [ ] detach from session: blocks indefinetly
- [ ] Session manager UI

### CODE REVIEW

**Comment by iXialumy** [comment]
Hey @jakob-ledermann 
What is the current progress with this. Is there anything we can work on together here?

**Comment by ulyssesdotcodes** [comment]
There's a ton of good work in here, so I'm hesitant to duplicate it on another branch, but there's enough refactoring and reformatting of shared windows/unix files that it might impede getting merged into the main repo. What are your thoughts @iXialumy?

I'll probably be able to spend a little time on this over the next few weeks, so I'd like to know where to focus efforts.

**Comment by jakob-ledermann** [comment]
> Hey @jakob-ledermann What is the current progress with this. Is there anything we can work on together here?

Currently I do have a lack of time to devote to this. I think I managed to identify parts of the deadlock, but do not have a solution yet: somehow the client is trying to `flush` after sending a message to the server, while the server does not seem to be listening any longer. Unfortunately Windows does not seem to provide any equivalent with OverlappedIO-API to flush the files.

Interestingly the deadlock only happens reliably (I haven't used this version enough to rule out the deadlock in any other situation) on client detach.

In addition I realized I do not have a strong grasp of the features zellij provides with in regards to sessions on other operating systems, so I have a hard time identifing missing behaviour. (I think testcases could help to a great degree here)

> There's a ton of good work in here, so I'm hesitant to duplicate it on another branch, but there's enough refactoring and reformatting of shared windows/unix files that it might impede getting merged into the main repo. What are your thoughts @iXialumy?
> 
> I'll probably be able to spend a little time on this over the next few weeks, so I'd like to know where to focus efforts.

Thanks for calling this good work. I am unsure if this way of using IPC is the right tool for this job, due to the above explained deadlock.

The code to record the session state is currently something I have a hard time to figure out what it should record, so that might be a useful avenue to get working?
I will probably be able to find more time especially for reading code and discussions the next few weekends as they are extended where I live.

**Comment by ulyssesdotcodes** [comment]
Thanks for the reply.

Mainly I think splitting ipc out might not merge well to zellij main. To
avoid that I got PipeStream working in a local branch by pulling in minimal
changes manually and putting named_pipe in a windows util directory. I can
either push that and make a PR from  those manual changes, or pull the
changes here and work backwards to preserve the commit history, whichever
you'd prefer.

I was hoping that having a single receiver/sender would fix the performance
issues, but it looks like those are still there. I can do some more digging
this week probably.

**Comment by jakob-ledermann** [comment]
You might be right, with that assessment. Another approach could be to get `interprocess` to change their handling of NamedPipes internally. Then we could keep the changes to `ipc.rs` much closer to zellij-org/zellij.

Can you quantify the performance problems? We might wan't to play around with the buffer configuration for the windows internal buffers of the named pipe and it is much easier to argue about performance after measuring the effects. I think I also managed to get that feeling of reduced performance on windows.

To pinpoint the deadlock issue with a single pipe I used a small isolated test project so that probably influenced how I incorporated the results over to zellij.

**Comment by ulyssesdotcodes** [comment]
True, getting interprocess to change their handling would also solve the issue.

Hard to quantify exactly - it just seems sluggish compared with running on Linux - more input delay, stuttery output. If you are able to install wsl, zellij through wsl should give you a good idea of what features zellij has and the speed comparison.

I'll redo my local changes on top of this branch and push for review.

**Comment by iXialumy** [comment]
This may also be possible with interprocess 2.0 as indicated [here](https://github.com/kotauskas/interprocess/issues/7)

That could bring us to use basically the same logic as with unix, just that we don't clone by file descriptor, but directly.

**Pull request merged**
